name: Cypress Cucumber tests
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    name: Run Cypress tests
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
      - name: upload test results
        uses: actions/upload-artifact@v4
        with:
          name: Test results artifact
          path: test-output
          if-no-files-found: ignore
